### ISSUE TITLE
Difficult to verify Supertokens

### ISSUE THREAD

**Issue by mikeghen** [superfluid-finance/custom-supertokens#15]
I was able to easily deploy a supertoken using these scripts but unfortnuately verify the contracts is proving to be difficult. I'm creating this issue to report that and to ask if you know how to verify these contract @ngmachado. I think it stems from using web3tx. Without easy verification it makes working with the token on mumbai polygonscan difficult.

**Comment by hellwolf** [comment]
@d10r will help you, who verifies all our contracts at the moment, including the super tokens.

**Comment by d10r** [comment]
thx for that feedback!
I just merged a change which allows verification via truffle plugin. Instructions are added to the README.
Please let me know if there's any issues left with that.

**Comment by mikeghen** [comment]
@d10r Awesome! Thank you, I will try it next time I deploy a token.
