### ISSUE TITLE
[BOUNTY] Super Token Wizard

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/custom-supertokens#25]
# [EXTERNAL] Super Token Wizard

## Problem

- As a developer or someone who wants to try out Superfluid, I’d like to be able to deploy a Super Token easily without having to hunt for the right contracts and parameters or manually configuring all of them
- I’d like to be able to quickly get a customized Super Token contract for my needs
- Ideally I’d like to be able to export to remix for further customization and deployment
- I can switch networks in the interface
- I’d like to deploy a Super Token contract directly from the interface, initiating a transaction in my wallet
- The UI should show me the deployed address afterwards

## Appetite

This project should take 4 weeks of development time to get to a functional MVP

## Solution

- The solution may take the form of a utility like the OpenZeppelin contract wizard https://wizard.openzeppelin.com/
- An MVP would generate contract code based on a few select inputs:
    - Token name
    - Token symbol
    - Premint quantity
    - Premint destination (default: deployer address)
    - Ad-hoc mint function (Ownable)

https://whimsical.com/super-token-wizard-FxPFgUiRnQthXs6VHdXeaT

## **Acceptance Criteria**

- [ ]  The app is available in a web interface
- [ ]  I can input a few parameters to customize the
    - [ ]  Name
    - [ ]  Token symbol
    - [ ]  Premint amount
- [ ]  I can enable or disable the following features
    - [ ]  Mintable
    - [ ]  Ownable (for the Mintable method)
- [ ]  I can copy and paste the contract code into remix and deploy
- [ ]  I can switch networks in the interface
- [ ]  I can 1-click deploy and initiate a wallet transaction from the deploy button
- [ ]  The UI should show me the deployed address afterwards

## Bounty Amount
$1000 in USDC on Polygon

## Rabbit holes

- In MVP, this feature does not need to include any other token configuration options aside from the above, however, these will be considered for follow-on bounties

## Notes

- Documentation on how to construct the Pure Super Token contracts is located here https://docs.superfluid.finance/superfluid/developers/super-tokens/deploy-a-super-token/deploying-a-pure-super-token
- Some example Super Tokens are available at https://github.com/superfluid-finance/custom-supertokens

**Comment by Salmandabbakuti** [comment]
Interesting. Count me in! The only challenge I foresee is compiling contracts directly on the browser. Nevertheless, This can be done.

**Comment by Seroxdesign** [comment]
Hello, I am interested in taking this task

**Comment by vmichalik** [comment]
> Hello, I am interested in taking this task

As previously discussed (day of posting the bounty!) this is yours, we'll endeavour to keep all assignment discussions in the thread in future so it's clearer when assigned - though the issue status in the bounties github project is assigned already

**Comment by d10r** [comment]
https://superfluid-wizard.huntersworkshop.xyz/
